name: logisim-evolution-snapcraft
icon: snap/gui/logisim-icon-128.png
license: GPL-3.0
summary: Logisim is a digital circuit simulator
description: |
  Github (compilation) : https://github.com/anrouxel/logisim-evolution-snapcraft
base: core20
grade: stable
confinement: strict

adopt-info: logisim-evolution-snapcraft

architectures:
  - build-on: amd64

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig

apps:
  logisim-evolution-snapcraft:
    extensions: [gnome-3-38]
    command: usr/lib/jvm/java-16-openjdk-amd64/bin/java -jar $SNAP/logisim/logisim-evolution.jar
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
    plugs:
      - gsettings
      - opengl
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - network

parts:     
  logisim-evolution-snapcraft:
    plugin: nil
    source: https://github.com/logisim-evolution/logisim-evolution.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags `git rev-list --tags --max-count=1`)" -b latest
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    override-build: |
      # Gets the host and port from a proxy URL
      #   $1 = the proxy URL, such as "http://10.10.10.1:8222/"
      getproxy () {
          # Parses URL with Bash or Dash shell parameter expansion
          tail=${1#http*://}
          head=${tail%%/*}
          host=${head%:*}
          port=${head##*:}
      }
      # Adds Java system properties using shell positional parameters
      set --
      if [ -n "${http_proxy:-}" ]; then
          getproxy "$http_proxy"
          set -- "$@" "-Dhttp.proxyHost=$host" "-Dhttp.proxyPort=$port"
      fi
      if [ -n "${https_proxy:-}" ]; then
          getproxy "$https_proxy"
          set -- "$@" "-Dhttps.proxyHost=$host" "-Dhttps.proxyPort=$port"
      fi
      # Builds JavaFX
      bash gradlew "$@" shadowJar
      cd build/libs
      mv *-all.jar logisim-evolution.jar
      mv logisim-evolution.jar $SNAPCRAFT_PART_INSTALL/
      cd $SNAPCRAFT_PART_INSTALL/
      mkdir logisim
      mv logisim-evolution.jar $SNAPCRAFT_PART_INSTALL/logisim
      cd $SNAPCRAFT_PART_INSTALL/
      tree $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - git
      - sed
      - openjdk-16-jdk
      - libfontconfig1-dev
      - tree
    stage-packages:
      - openjdk-16-jre
      - fonts-freefont-ttf
      - fonts-arphic-uming
      - fontconfig-config
